name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag windevops:latest
    - name: Run Docker image
      run: docker run --name windevops-container windevops:latest
    - name: Export WSL image as tar file
      run: docker export --output=windevops.tar windevops-container
